### ISSUE TITLE
Локализация docs/api/components/nuxt-island.md

### ISSUE THREAD

**Issue by JonikUl** [translation-gang/nuxt#53]
REF: https://nuxt-ru.vercel.app/docs/api/components/nuxt-island

**Comment by mnenie** [comment]
беру

**Comment by Hekikai** [comment]
@mnenie мне нравится "островной компонент", либо "island-компонент". Надо поголосовать))

**Comment by mnenie** [comment]
@Hekikai я за островной компонент)
