### ISSUE TITLE
Локализация docs/api/composables/use-router.md

### ISSUE THREAD

**Issue by JonikUl** [translation-gang/nuxt#92]
REF: https://nuxt-ru.vercel.app/docs/api/composables/use-router

**Comment by mnenie** [comment]
беру на себя

**Comment by mnenie** [comment]
@Hekikai как думаешь, как лучше перевести history ( -history stack, -history mode) ?

посмотрел в доку vue router там оставляли history непереведенным, думаю можно оставить так, но тут уже не знаю как лучше будет))

**Comment by Ibochkarev** [comment]
> @Hekikai как думаешь, как лучше перевести history ( -history stack, -history mode) ?
> 
> посмотрел в доку vue router там оставляли history непереведенным, думаю можно оставить так, но тут уже не знаю как лучше будет))

Оставляем history
